### ISSUE TITLE
initial review before submission

### ISSUE THREAD

**Issue by LiNk-NY** [waldronlab/MicrobiomeBenchmarkData#2]
Hi Samuel, @sdgamboa 

The package looks in good shape.
I have some comments below. 

Best,
Marcel

---

# MicrobiomeBenchmarkData

## DESCRIPTION

- [x] Looks good.
- [x] There is a typo in the `Description`.

## NAMESPACE

- [x] Avoid generic names such as `getDataset` and use a name like
`getBenchmarkData`
- [x] You can use the base pipe operator (`|>`) instead of importing the one from
`magrittr`.
- [x] For packages where you import only one function, you may want to consider
putting them in the `Suggests` field.

## vignettes

- [x] Include a description of what the vignette does and what the code is doing
(`datasets.Rmd`).
- [x] Consider using `BiocStyle` in the vignettes.
- [x] Use template code for the installation section from any Bioconductor landing
page, i.e., use `require` or `requireNamespace`.
- [x] Perhaps `getDataset` should return an object that can be used, e.g.,
`data.frame` with additional metadata
- [x] `removeCache()` with `n` returns:
```
Error in BiocFileCache::removebfc(cache, ask = interactive()) :
  object 'doit' not found
```

## R

- [x] It looks like you may only want to use `bfcrpath` with `exact = TRUE`
instead of the series of `if else` statements in `.getResourcePath`.
- [x] `sampleMetadata` does not need to be documented and exported.

## tests

- [x] Package coverage looks good

```r
covr::package_coverage()
#' MicrobiomeBenchmarkData Coverage: 74.23%
#' R/MicrobiomeBenchmarkData.R: 74.23%
```

**Comment by sdgamboa** [comment]
@LiNk-NY, thanks for the feedback! I addressed all the points above. Some relevant changes I made to the code based on the feedback:

> It looks like you may only want to use bfcrpath with exact = TRUE
instead of the series of if else statements in .getResourcePath.

+ I adapted the code to be more like the example provided in the BiocFileCache vignette:
https://github.com/waldronlab/MicrobiomeBenchmarkData/blob/cb7a34cc62e7ec70d32118d075ca3264615ee3aa/R/MicrobiomeBenchmarkData.R#L209-L242

> removeCache() with n returns error
+ It seems that the error in removeCache with 'no' is in the BiocFileCache package. Maybe I need to write an issue there. I added some code to avoid the error: https://github.com/waldronlab/MicrobiomeBenchmarkData/blob/cb7a34cc62e7ec70d32118d075ca3264615ee3aa/R/MicrobiomeBenchmarkData.R#L81-L109

## Regarding some other commentaries

>For packages where you import only one function, you may want to consider
putting them in the Suggests field.

+ I removed unnecessary dependencies. I kept some packages in 'Imports' with only one function, but these packages are imported by TreeSummarizedExperiment (ape) or are already installed in base R (tools, utils). So I don't think this would be a problem.

>Perhaps getDataset should return an object that can be used, e.g.,
data.frame with additional metadata.

+ Just to clarify, the function (now getBenchmarkData) already returns a list of TreeSummarizedExperiments (with the dryrun = FALSE argument). Or do you mean something else?

``` r
suppressMessages({
    library(MicrobiomeBenchmarkData)
    x <- getBenchmarkData(dryrun = FALSE)
})
#> Warning: No taxonomy_tree available for Ravel_2011_16S_BV.
#> Warning: No taxonomy_tree available for Stammler_2016_16S_spikein.
lapply(x, class)[[1]]
#> [1] "TreeSummarizedExperiment"
#> attr(,"package")
#> [1] "TreeSummarizedExperiment"
```

<sup>Created on 2022-08-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

>sampleMetadata does not need to be documented and exported.
+ @lwaldron, I think we discussed at some point that the sampleMetadata should be exported as a merged table. What do you think?

**Comment by LiNk-NY** [comment]
Hi Samuel, @sdgamboa 

Sorry I missed the follow up. 

> * I adapted the code to be more like the example provided in the BiocFileCache vignette:
>   https://github.com/waldronlab/MicrobiomeBenchmarkData/blob/cb7a34cc62e7ec70d32118d075ca3264615ee3aa/R/MicrobiomeBenchmarkData.R#L209-L242
> 

This solution was simple and short for URLs: 

https://github.com/Bioconductor/AnnotationForge/blob/3e01d4f3620396578eee7783849589fe8d4b23aa/vignettes/MakingNewAnnotationPackages.Rnw#L196-L201

> > removeCache() with n returns error
> 
> * It seems that the error in removeCache with 'no' is in the BiocFileCache package. Maybe I need to write an issue there. I added some code to avoid the error: https://github.com/waldronlab/MicrobiomeBenchmarkData/blob/cb7a34cc62e7ec70d32118d075ca3264615ee3aa/R/MicrobiomeBenchmarkData.R#L81-L109
> 

I don't remember the original code used here. Note that if all conditions `return(invisible(NULL))`, then perhaps move this out of the `if` statements. It would be good to minimize what Martin terms "[cyclomatic complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity)" by doing type checking near the top of the function and only presenting behavior for one condition instead of using nested `if` / `else` statements. Either way, it works. 

> ## Regarding some other commentaries
> > For packages where you import only one function, you may want to consider
> > putting them in the Suggests field.
> 
> * I removed unnecessary dependencies. I kept some packages in 'Imports' with only one function, but these packages are imported by TreeSummarizedExperiment (ape) or are already installed in base R (tools, utils). So I don't think this would be a problem.
> 

You can run an analysis with `pkgndep` and get recommendations. 

> > Perhaps getDataset should return an object that can be used, e.g.,
> > data.frame with additional metadata.
> 
> * Just to clarify, the function (now getBenchmarkData) already returns a list of TreeSummarizedExperiments (with the dryrun = FALSE argument). Or do you mean something else?
> 

I think when `dryrun = TRUE`, the user should get a `data.frame` of available datasets with additional metadata, if possible. This could also be a separate function. 

> ```r
> suppressMessages({
>     library(MicrobiomeBenchmarkData)
>     x <- getBenchmarkData(dryrun = FALSE)
> })
> #> Warning: No taxonomy_tree available for Ravel_2011_16S_BV.
> #> Warning: No taxonomy_tree available for Stammler_2016_16S_spikein.
> lapply(x, class)[[1]]
> #> [1] "TreeSummarizedExperiment"
> #> attr(,"package")
> #> [1] "TreeSummarizedExperiment"
> ```
> 
> Created on 2022-08-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)
> 
> > sampleMetadata does not need to be documented and exported.
> 
> * @lwaldron, I think we discussed at some point that the sampleMetadata should be exported as a merged table. What do you think?

Is the intent to have users make use of this data? Otherwise, it could be an internal dataset (or as part of the results for when `dryrun = TRUE` if it is relevant to the function above). 

Also, note that `LazyData: false` requires the use of `data("datasetname", package = "packagename")` construction in examples, vignettes, and @usage documentation.

Best,
Marcel

**Comment by sdgamboa** [comment]
The package has been accepted ([here](https://github.com/Bioconductor/Contributions/issues/2791#issuecomment-1292432939)), so I'm closing this issue.
